
# This specification sets up an environment similar to Euler's and clones
# a fresh copy of the upstream homework files to test against.
#
# The spec isn't called directly, instead it is used as a base configuration for
# further tasks to "extend".
.euler-ish:
  tags:
  - me459
  image:
    name: fedora:33
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - uname -a
    - dnf groupinstall -y 'Development Tools'
    - git clone https://github.com/DanNegrut/ME459 upstream_files


# This specification builds HW06 from an sh-compatible script
build-hw06:
  stage: build
  artifacts:
    expire_in: 60m
    paths: 
      - HW06/task2
  extends: .euler-ish
  script:
    - cp upstream_files/assignments/2021/HW06/* HW06/
    - cd HW06
    - gcc dll_alloc.c task2.c traversal.c -Wall -O3 -o task2


# This specification tests the program that was built in the "build" stage for
# a couple of different inputs
test-hw06:
  stage: test
  needs: ["build-hw06"]
  dependencies: ["build-hw06"]
  extends: .euler-ish
  script:
    - cd HW06
    - ./task2 4
    - ./task2 8
    - ./task2 16
    - ./task2 25

